### ISSUE TITLE
Flutter 3.10.x support

### ISSUE THREAD

**Issue by danielgomezrico** [la-haus/flutter-twilio-conversations#16]
If you set the version on pubspec:  

```yaml
environment:
  sdk: 3.0.1
  flutter: 3.10.1
```

The app crashes with:
```console
The current Dart SDK version is 3.0.1.

Because adviser depends on twilio_conversations from git which requires SDK version 2.19.6, version solving failed.
```
